# Generated by Django 3.1.5 on 2022-01-21 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='country_of_origin',
        ),
        migrations.RemoveField(
            model_name='person',
            name='date_of_birth',
        ),
    ]
