# Generated by Django 3.1.5 on 2022-01-21 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_person_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='country_of_origin',
            field=models.CharField(default='NA', max_length=64),
            preserve_default=False,
        ),
    ]
