# Generated by Django 3.1.5 on 2022-01-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220127_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date_of_birth',
            field=models.DateField(verbose_name='Date of Birth: YYYY-MM-DD'),
        ),
    ]
